# Tensor Manipulation

- Scalar: 우리가 흔히 알고 있는 상수, 하나의 값을 표현. Rank = 0
- Vector: 여러 개의 값을 가진 1차원 데이터. Rank = 1
- Matrix: 행렬, 행과 열로 이루어진 2차원 데이터. Rank = 2
- Tensor: n 차원의 행렬 형태로 표현. scalar는 0차원, vector는 1차원, matrix는 2차원 텐서라고 할 수 있음. Rank = n
- e.g.: 가로, 세로 사이즈가 100인 컬러 이미지(RGB) 1장은 [3, 100, 100]의 3-d tensor로 저장.
    - 만약 위 사진과 같은 사이즈의 이미지가 5장이 있다면, [5, 3, 100, 100]의 4-d tensor로 저장.

In [1]:
import numpy as np
import torch

# 1. Create a Tensor

## 1.1. torch.tensor()

In [2]:
torch.tensor(5) # 0-d tensor = scalar

tensor(5)

In [3]:
torch.tensor([1, 2, 3, 4, 5]) # 1-d tensor = vector

tensor([1, 2, 3, 4, 5])

In [8]:
torch.tensor([[1, 2, 3], [4, 5, 6]]) # 2-d tensor = matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
torch.tensor([[1], [2], [3], [4], [5]]) # 5-d tensor

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

In [6]:
temp_list = [1, 2, 3, 4, 5]
torch.tensor(temp_list) # 1-d tensor = vector

tensor([1, 2, 3, 4, 5])

In [7]:
temp_set = {1, 2, 3, 4, 5}
torch.tensor(temp_list) # 5-d tensor

tensor([1, 2, 3, 4, 5])

In [9]:
temp_tuple = (1, 2, 3, 4, 5)
torch.tensor(temp_tuple) # 5-d tensor

tensor([1, 2, 3, 4, 5])

In [11]:
temp_np_array = np.array(temp_list)
torch.tensor(temp_np_array)

tensor([1, 2, 3, 4, 5])

In [12]:
torch.from_numpy(temp_np_array)

tensor([1, 2, 3, 4, 5])

## 1.2. torch.ones()

In [13]:
torch.ones(3)

tensor([1., 1., 1.])

In [24]:
torch.ones([4, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
torch.ones([2, 4, 3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

## 1.3. torch.zeros()

In [16]:
torch.zeros(3)

tensor([0., 0., 0.])

In [17]:
torch.zeros([3, 3])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
torch.zeros([3, 4, 5])

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [28]:
torch.zeros([5, 3, 1, 4])

tensor([[[[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]]]])

## 1.3. torch.arange()

In [25]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
torch.arange(22, 10, -1)

tensor([22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [32]:
torch.arange(10, 22, 2)

tensor([10, 12, 14, 16, 18, 20])

## 1.4. torch.rand()

In [29]:
torch.rand(5)

tensor([0.1522, 0.1697, 0.2454, 0.1852, 0.4975])

In [30]:
torch.rand([5, 5])

tensor([[0.0317, 0.5140, 0.2283, 0.5707, 0.4012],
        [0.6782, 0.3302, 0.7862, 0.8646, 0.0300],
        [0.3528, 0.9690, 0.1262, 0.8522, 0.0647],
        [0.8909, 0.0543, 0.2557, 0.8402, 0.7074],
        [0.7058, 0.0457, 0.3413, 0.3127, 0.7692]])

## 1.5. torch.xxx_like()

In [34]:
a = torch.zeros(5)
torch.ones_like(a)

tensor([1., 1., 1., 1., 1.])

In [35]:
torch.zeros_like(a)

tensor([0., 0., 0., 0., 0.])

In [36]:
torch.rand_like(a)

tensor([0.3496, 0.8052, 0.5345, 0.8157, 0.8720])

# 2. Attribute: shape, dtype, device

## 2.1. Tensor.shape

In [41]:
a = torch.tensor([1, 2, 3, 4, 5])
a.shape

torch.Size([5])

In [42]:
b = torch.tensor(5)
b.shape

torch.Size([])

## 2.2. Tensor.dtype

In [38]:
a.dtype

torch.int64

In [47]:
# pytorch data type
float_tensor = torch.ones([3, 5, 5], dtype = torch.float64)
double_tensor = torch.ones(1, dtype = torch.double)
complex_float_tensor = torch.ones(1, dtype = torch.complex64)
complex_double_tensor = torch.ones(1, dtype = torch.complex128)
int_tensor = torch.ones(1, dtype = torch.int)
long_tensor = torch.ones(1, dtype = torch.long)
uint_tensor = torch.ones(1, dtype = torch.uint8)
bool_tensor = torch.ones(1, dtype = torch.bool)

float_tensor.dtype

torch.float64

In [48]:
float_tensor

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]], dtype=torch.float64)

## 2.3. Tensor.device

In [46]:
a = torch.arange(1, 6)
a

tensor([1, 2, 3, 4, 5])

In [49]:
a.device

device(type='cpu')

In [51]:
torch.cuda.is_available() # GPU가 NVIDA일 때
# a = torch.arange(1, 6).to('cuda')
# a = torch.arange(1, 6).cuda()

False

In [53]:
# 맥북
print(f"MPS 장치를 지원하도록 build가 되었는가? {torch.backends.mps.is_built()}")
print(f"MPS 장치가 사용 가능한가? {torch.backends.mps.is_available()}") 

MPS 장치를 지원하도록 build가 되었는가? True
MPS 장치가 사용 가능한가? True


In [54]:
device = torch.device('mps:0' if torch.backends.mps.is_available() else 'cpu')

In [66]:
a = torch.arange(1, 6).to('mps')

In [67]:
a.device

device(type='mps', index=0)

# 3. Tensor Aggregation: element wise 연산, min, max, mean

## 3.1. element wise 연산: tensor의 같은 자리 원소들끼리 산술 연산

In [69]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [70]:
print(a.add(b))
print(a.sub(b))
print(a.mul(b))
print(a.div(b))

tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


## 3.2. inplace 연산
- 함수 뒤에 _를 붙이면 자기 자신의 값을 바꾸게 됨
- 연산 결과를 반환하면서 동시에 자기 자신의 데이터를 고침

In [71]:
print(a.add(b))
print(a)
print(a.add_(b))
print(a)

tensor([[ 6,  8],
        [10, 12]])
tensor([[1, 2],
        [3, 4]])
tensor([[ 6,  8],
        [10, 12]])
tensor([[ 6,  8],
        [10, 12]])


## 3.3. Tensor.min()
- 가장 작은 값을 반환해줌
- argument로 차원을 넣어주면 해당 차원에서 각각 가장 작은 값들과, 그 값들의 위치를 함께 반환

In [72]:
a = torch.tensor([[3, 1, 4], [2, 4, 5]])
print(a.shape)
print(a.min())
print(a.min(dim = 0))
print(a.min(dim = 1))

torch.Size([2, 3])
tensor(1)
torch.return_types.min(
values=tensor([2, 1, 4]),
indices=tensor([1, 0, 0]))
torch.return_types.min(
values=tensor([1, 2]),
indices=tensor([1, 0]))


## 3.4. Tensor.max()
- 가장 큰 값을 반환해줌
- argument로 차원을 넣어주면 해당 차원에서 각각 가장 작은 값들과, 그 값들의 위치를 함께 반환

In [73]:
a = torch.tensor([[3, 1, 4], [2, 4, 5]])
print(a.shape)
print(a.max())
print(a.max(dim = 0))
print(a.max(dim = 1))

torch.Size([2, 3])
tensor(5)
torch.return_types.max(
values=tensor([3, 4, 5]),
indices=tensor([0, 1, 1]))
torch.return_types.max(
values=tensor([4, 5]),
indices=tensor([2, 2]))


## 3.5. Tensor.mean()

In [76]:
a = torch.FloatTensor([[3, 1, 4], [2, 4, 5]])
print(a.shape)
print(a.mean())
print(a.mean(dim = 0))
print(a.mean(dim = 1))

torch.Size([2, 3])
tensor(3.1667)
tensor([2.5000, 2.5000, 4.5000])
tensor([2.6667, 3.6667])


# 4. Indexing
- 원하는 원소나 영역을 index를 이용하여 선택
- 기존의 numpy, pandas의 indexing과 유사