In [2]:
import numpy as np
from numpy.linalg import norm

# Updated user ratings
alice = np.array([5, 3, 4, 4, 0])  # Alice has not rated the fifth item
user1 = np.array([3, 1, 2, 3, 3])
user2 = np.array([4, 3, 4, 3, 5])
user3 = np.array([3, 3, 1, 5, 4])
user4 = np.array([1, 5, 5, 2, 1])

# Compile all ratings into a matrix
ratings = np.array([alice, user1, user2, user3, user4])

def cosine_similarity(u1, u2):
    """Computes cosine similarity between two vectors."""
    return np.dot(u1, u2) / (norm(u1) * norm(u2))

# Compute the similarity matrix
num_users = ratings.shape[0]
similarity_matrix = np.zeros((num_users, num_users))

for i in range(num_users):
    for j in range(num_users):
        if i != j:
            similarity_matrix[i, j] = cosine_similarity(ratings[i], ratings[j])
        else:
            similarity_matrix[i, j] = 0  # exclude self-similarity

print("Similarity Matrix:\n", similarity_matrix)

Similarity Matrix:
 [[0.         0.82686887 0.81016272 0.76277007 0.78954203]
 [0.82686887 0.         0.95938348 0.9356927  0.63781505]
 [0.81016272 0.95938348 0.         0.89442719 0.77151675]
 [0.76277007 0.9356927  0.89442719 0.         0.63831064]
 [0.78954203 0.63781505 0.77151675 0.63831064 0.        ]]
